### ISSUE TITLE
Blender cannot be installed download

### ISSUE THREAD

**Issue by xiaoxiaobx** [davidemarelli/sfm_flow#1]
hello,@Davide Marelli
How to install and download the free Blender, the version that students can use?

**Comment by davidemarelli** [comment]
Hello, the add-on works with Blender version 2.80.75 or above.
You can freely download Blender 2.83.8 from [https://www.blender.org/download/lts/#lts-release-2838](https://www.blender.org/download/lts/#lts-release-2838).

**Comment by xiaoxiaobx** [comment]
Hello.davide marelli
Thank you very much!


Excuse me, please ask another question.&nbsp;
I see the software used to evaluate the model in your introduction. Where can I download the software used for model evaluation?
I can't find the relevant link. Can you give a link to the software for evaluating the model?







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "davidemarelli/sfm_flow"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月10日(星期二) 凌晨0:52
收件人:&nbsp;"davidemarelli/sfm_flow"<sfm_flow@noreply.github.com&gt;;
抄送:&nbsp;"专属bx"<775096562@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [davidemarelli/sfm_flow] Blender cannot be installed download (#1)





 
Hello, the add-on works with Blender version 2.80.75 or above.
 You can freely download Blender 2.83.8 from https://www.blender.org/download/lts/#lts-release-2838.

**Comment by davidemarelli** [comment]
You can download SfM Flow from the release page [https://github.com/davidemarelli/sfm_flow/releases](https://github.com/davidemarelli/sfm_flow/releases). Here is the [direct link to v1.0.0](https://github.com/davidemarelli/sfm_flow/releases/download/v1.0.0/SfM-Flow_v1.0.0.zip).

For instructions on how to install and use it, please refer to [Getting started](https://github.com/davidemarelli/sfm_flow/wiki/Getting-started) wiki page.
